[build]
  command = "python -m pip install --upgrade pip && pip install -r requirements.txt && pelican content"
  publish = "output"

[build.environment]
  PYTHON_VERSION = "3.11"
  PYTHON_CMD = "python3"
  PIP_CMD = "pip3" 